services:
  fundmate-db:
    image: postgres
    restart: unless-stopped
    env_file:
      - .env.db
    ports:
      - 5432:5432
    volumes:
      - fundmate-app:/var/lib/postgresql/data
  fundmate-client:
    image: client
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./frontend/
        target: /usr/src/app/
      - type: volume
        target: /usr/src/app/node_modules
      - type: bind
        source: ./frontend/vite.config.js
        target: /usr/src/app/vite.config.js
    ports:
      - 5173:5173
  fundmate-nginx:
    image: fundmate-nginx
    restart: unless-stopped
    build:
      context: ./frontend/
      dockerfile: Dockerfile.prod
    ports:
      - 8085:80
  fundmate-api:
    image: fundmate-api
    restart: unless-stopped
    depends_on:
      - fundmate-db
    build:
      context: ./api/
      dockerfile: ./Dockerfile
    ports:
      - 8081:8080
    env_file:
      - .env.api
volumes:
  fundmate-app:
